### ISSUE TITLE
Question about the evaluation of CoNLL-2005 in the end-to-end setting.

### ISSUE THREAD

**Issue by KiroSummer** [strubell/LISA#9]
Hi, I have a question about the evaluation in the end-to-end setting.
When I study the code, I found your evaluation of CoNLL-2005 is different from He et al. (2018) [https://github.com/luheng/lsgn/blob/master/srl_eval_utils.py] in line 190-207.
Then, I conduct some evaluation experiments with the following two files (gold file and system file)

gold file:
```
  -                (AM-LOC*               *
  -                       *               *
  -                       *               *
  -                       *               *
  -                       *)              *
  -                       *               *
  -                    (A0*)              *
  call                  (V*)              *
  -                    (A1*               *
  -                       *            (A1*
  -                       *)              *)
  -                    (A2*               *
  -                       *               *
  -                       *               *
  -                       *               *
  -                       *               *
  discipline              *             (V*)
  -                       *               *
  -                       *        (AM-MNR*
  -                       *               *
  -                       *               *
  -                       *               *
  -                       *)              *)
  -                       *               *
```

system file:
```
  -                (AM-LOC*               *
  -                       *               *
  -                       *               *
  -                       *               *
  -                       *)              *
  -                       *               *
  -                    (A0*)              *
  call                  (V*)              *
  -                    (A1*               *
  -                       *            (A1*
  -                       *)              *)
  -                    (A2*               *
  -                       *               *
  -                       *               *
  -                       *               *
  -                       *               *
  -                       *              *
  ,                       *               (V*)
  -                       *        (AM-MNR*
  -                       *               *
  -                       *               *
  -                       *               *
  -                       *)              *)
  -                       *               *
```

After running the evaluation script, we get the results as follows:
```
WARNING : sentence 0 : verb discipline at position 16 : missing predicted prop! Counting all arguments as missed!
Number of Sentences    :           1
Number of Propositions :           2
Percentage of perfect props :  50.00

              corr.  excess  missed    prec.    rec.      F1
------------------------------------------------------------
   Overall        4       0       2   100.00   66.67   80.00
----------
        A0        1       0       0   100.00  100.00  100.00
        A1        1       0       1   100.00   50.00   66.67
        A2        1       0       0   100.00  100.00  100.00
    AM-LOC        1       0       0   100.00  100.00  100.00
    AM-MNR        0       0       1     0.00    0.00    0.00
------------------------------------------------------------
         V        1       0       1   100.00   50.00   66.67
------------------------------------------------------------
```

The evaluation script only gives the correctly predicted number of 4, excess number of 0, and missed number of 2.
And the script warns that the second predicate ``discipline'' is missed and counting all arguments as missed.
In my mind, I think the precision should be 4 / (4 + 2), where 2 is the number of wrongly predicted predicates' arguments.
But in your code, you missed the number of wrongly predicted predicates' arguments, which would result in higher precision.

Did I miss something or understand something wrongly?

Thank you very much for your reply!

**Comment by strubell** [comment]
hi, sorry I'm just seeing this! The conll eval scripts are copied directly from the official scripts provided by the shared task [here](https://www.cs.upc.edu/~srlconll/soft.html#srlconll) (I don't know perl!) So, if there is an error in the script, then that would be a mistake that everyone using those evaluation scripts would have shared? Or, are you saying there's something wrong with the system output?

**Comment by KiroSummer** [comment]
Thank you for your reply. There is no error in the evaluation script. However, the script is designed for the given-predicate setting. Therefore, when we use it in the end-to-end setting, it would output some warnings that some propositions of the gold file are not counted. I think we need to use the evaluation script twice in the end-to-end setting as described in [LSGN](https://github.com/luheng/lsgn/blob/master/srl_eval_utils.py) (line 190-207).

**Comment by strubell** [comment]
Oh, wow! I think you're right, I didn't realize the script wasn't counting the incorrect predictions as excess/fps. Thanks for sharing this. I hope this discrepancy didn't cause you too much confusion or extra effort to figure out.
